pipeline {
    agent any

    environment {
        DOCKER_REPO = "rifaz15072000/frontend-nodejs"
        DOCKER_CREDENTIALS = "docker-cred"
        IMAGE_TAG = "1.0.${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Rifaz15072000/DevOps-Assignment-PG-AGI.git'
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS) {

                        def image = docker.build("${DOCKER_REPO}:${IMAGE_TAG}", "frontend/")

                        // Push version tag
                        image.push("${IMAGE_TAG}")

                        // Also push latest
                        image.push("latest")
                    }
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh """
                docker pull ${DOCKER_REPO}:${IMAGE_TAG}

                docker stop frontend-app || true
                docker rm frontend-app || true

                docker run -d \
                  --name frontend-app \
                  -p 3000:3000 \
                  ${DOCKER_REPO}:${IMAGE_TAG}
                """
            }
        }
    }
}

