pipeline {
    agent any

    environment {
        DOCKER_REPO = "rifaz15072000/backend-fastapi"
        DOCKER_CREDENTIALS = "docker-cred"
        CONTAINER_NAME = "backend-app"
        VERSION = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Rifaz15072000/DevOps-Assignment-PG-AGI.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', DOCKER_CREDENTIALS) {

                        def image = docker.build("${DOCKER_REPO}:${VERSION}", "backend/")

                        image.push()          // Push version tag
                        image.push("latest")  // Push latest tag
                    }
                }
            }
        }

        stage('Deploy Backend Container') {
            steps {
                sh '''
                echo "Pull latest image"
                docker pull ${DOCKER_REPO}:latest

                echo "Stop old container if exists"
                docker stop ${CONTAINER_NAME} || true
                docker rm ${CONTAINER_NAME} || true

                echo "Run new container"
                docker run -d \
                  --name ${CONTAINER_NAME} \
                  -p 8000:8000 \
                  ${DOCKER_REPO}:latest
                '''
            }
        }
    }

    post {
        success {
            echo "Backend deployed successfully!"
        }
        failure {
            echo "Backend deployment failed!"
        }
    }
}

