pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        ECR_REPO_FRONTEND = '<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/frontend'
        ECR_REPO_BACKEND = '<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/backend'
    }

    stages {
        stage('Checkout') {
            steps { git 'https://github.com/YOUR_USERNAME/DevOps-Assignment-PG-AGI.git' }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker build -t frontend ./frontend'
                sh 'docker build -t backend ./backend'
            }
        }

        stage('Push to ECR') {
            steps {
                sh 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_FRONTEND'
                sh 'docker tag frontend:latest $ECR_REPO_FRONTEND:latest'
                sh 'docker push $ECR_REPO_FRONTEND:latest'

                sh 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_BACKEND'
                sh 'docker tag backend:latest $ECR_REPO_BACKEND:latest'
                sh 'docker push $ECR_REPO_BACKEND:latest'
            }
        }

        stage('Terraform Init & Apply') {
            steps {
                dir('terraform') {
                    sh 'terraform init -backend-config=env/${ENVIRONMENT}/backend.tfvars'
                    sh 'terraform plan -var-file=env/${ENVIRONMENT}/backend.tfvars'
                    sh 'terraform apply -auto-approve -var-file=env/${ENVIRONMENT}/backend.tfvars'
                }
            }
        }
    }
}
